extends: default

rules:
  document-start: disable
  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
  line-length:
    max: 120
  comments-indentation: disable
  indentation:
    spaces: 2
    indent-sequences: whatever
